[project]
name = "todoist-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.3.4",
    "mcp[cli]>=1.9.0",
    "python-dotenv>=1.1.0",
    "todoist-api-python>=3.1.0",
]
